### ISSUE TITLE
Blank screen with Tiger Heli with version 0.1.2

### ISSUE THREAD

**Issue by davewongillies** [antongale/arcade-slapfight#1]
### Version (or build number)

0.1.2

### Steps to reproduce

- Load up Tiger Heli with version 0.1.2 of the core
- Game doesn't load, you just get a blank screen

### Expected Behavior

- Load game successfully with no blank screen

### Actual Behavior

- Game doesn't load, you just get a blank screen

### Additional Context

I rolled back to version 0.1.1 and could load Tiger Heli again

**Comment by antongale** [comment]
This isn't a bug, the new revision needs a new ROM file.  The MRA files are in the release so you can build your own.
